using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class FetishDB : MonoBehaviour {

	public List<string> verbs = new List<string>(){
		"Dominating",
		"Fisting",
		"Fucking",
		"Forgetting",
		"Fingering",
		"Going down on",
		"Stimulating",
		"Synergizing with",
		"Blowing",
		"Sexing",
		"Having intercourse with",
		"Submitting to",
		"Whipping",
		"Spanking",
		"Dressing up as",
		"Knowing (in the Biblical way)",
		"Laughing at",
		"Tickling",
		"Handcuffing",
		"Annoying",
		"Peeing on",
		"Videotaping",
		"Urinating on",
		"Penis fencing with",
		"Displaying",
		"Mounting",
		"Utilizing",
		"Pitching",
		"Catching",
		"Carpet munching",
		"Being abducted by",
		"Being gangbanged by",
		"Being probed by",
		"Probing",
		"Jizzing all over",
		"Penetrating",
		"Groping",
		"Cutting",
		"Jerking off to",
		"Tying up",
		"Sniffing",
		"Being peed on by",
		"Squeezing",
		"Arguing with",
		"Pretending to be",
		"Showering with",
		"Yelling at",
		"Watching",
		"Being vomited on by",
		"Vomiting on",
		"Female ejaculation by",
		"Eating",
		"Being naked with",
		"Thrusting into",
		"Scissoring",
		"Cuddling with",
		"Galvinizing",
		"Singing to",
		"Figuratively sleeping with",
		"Literally sleeping with",
		"Orgies with",
		"Rimming",
		"Seducing",
		"Fornicating with",
		"Dry humping",
		"Massaging",
		"Lubing up",
		"Sodomizing",
		"Sixty-nining",
		"Caressing",
		"Sauteeing", 
		"Babysitting",
		"Farting at",
		"Menstruating on",
		"Working out with",
		"Deflowering",
		"Facebook stalking",
		"Biting",
		"Queefing under",
		"Stroking",
		"Riding",
		"Defecating on",
		"Doing drugs with",
		"Discussing politics with",
		"Flossing after",
		"Not being able to even with",
		"Frolicking with",
		"Starting a sex cult with",
		"Procrastinating with",
		"Rectally examaning",
		"Moaning at the sight of",
		"Lending my old team jacket to",
		"Collecting",
		"Drinking fine wine with",
		"Playing pretend with",
		"Fighting",
		"Getting hit by",
		"Stomping on",
		"Dreaming about",
		"Smothering"
	};

	public List<string> nouns = new List<string>(){
		"ostriches",
		"books",
		"Mitt Romney",
		"my computer",
		"someone's hair",
		"a pale immitation of Carl Sagan",
		"God",
		"very tiny things",
		"spicy ramen noodles",
		"a poster of Richard Simmons",
		"plants",
		"tentacles",
		"cats",
		"furries",
		"an English literature professor",
		"clowns",
		"furniture",
		"mannequins",
		"bros",
		"aliens",
		"bald women",
		"the elderly",
		"Milo Something",
		"nuns",
		"librarians",
		"the entire Blue Man Group",
		"firefighters",
		"androgynous bodybuilders",
		"police officers",
		"postal workers",
		"oxen",
		"mermaids",
		"Cthulhu",
		"goth chicks",
		"Superman",
		"genderqueer people",
		"triangles",
		"cyberpunks",
		"phallic vegetables",
		"guitarists",
		"a David Bowie impersonator",
		"guitars",
		"lightbulbs",
		"bears (in the gay way)",
		"bears (in the mammal way)",
		"bestselling authors",
		"typewriters",
		"cactuses",
		"glass",
		"soldiers",
		"exotic dancers",
		"food",
		"needles",
		"blood",
		"politicians",
		"stewardesses",
		"red heads",
		"bellybuttons",
		"shoes",
		"peanut butter",
		"latex gloves",
		"conjoined twins",
		"lizards",
		"chocolate",
		"freshly butchered meat",
		"dental dams",
		"prostitutes",
		"undulating midsections",
		"pimps",
		"biceps",
		"nipples",
		"perky tits",
		"goats",
		"marzipan",
		"psychics",
		"swords",
		"cakes",
		"insects",
		"cold hard cash",
		"priests",
		"my ex",
		"pubes",
		"unicorns",
		"lips",
		"athletes",
		"convicts",
		"devil worshippers",
		"metal heads",
		"cyborgs",
		"hipsters",
		"robots",
		"toads",
		"Neck Face",
		"vampires",
		"clunky old cellphones",
		"literally any ancient trickster god",
		"slash fiction writers",
		"people with derpy smiles ",
		"fire eaters ",
		"thick, thick sausages"
	};

	public List<string> flavor = new List<string>(){
		"in the butt",
		"in a cemetary",
		"on the tarmac",
		"while drinking soda",
		"in the face",
		"in SPACE",
		"at the doctor's office",
		"with my hair",
		"against my feet",
		"in the library",
		"while on Facebook",
		"in the mouth",
		"under the balls",
		"between the dicks",
		"in the armpit",
		"up the cunt",
		"on the underboob",
		"in a gorilla suit",
		"who I met on OKCupid",
		"in missionary position",
		"right after church",
		"right before church",
		"with a spreadsheet",
		"with a quartz dildo",
		"at raves",
		"at the gay pride parade",
		"during work",
		"with peanut butter",
		"while listening to a recording of myself",
		"into a volcano",
		"who remind me of my grandmother",
		"in a swimming pool full of jello",
		"with boots on",
		"on top of old smokey",
		"on a bed of nails",
		"while skydiving",
		"while fully clothed",
		"while stoned",
		"with a medium-sized cactus",
		"covered in chocolate syrup",
		"and then being disgusted with myself",
		"while wearing glasses",
		"tenderly",
		"on the sidewalk",
		"up the nose",
		"on the nipples",
		"on the neck",
		"between the toes",
		"dressed head to toe in leather",
		"on a beach",
		"without them knowing",
		"but not in a creepy way",
		"while menstruating",
		"while reading the dictionary out loud",
		"while watching with a mirror",
		"while on fire",
		"without a condom",
		"with a boner",
		"in the early moonlight",
		"(*rimshot*)",
		"at band camp",
		"behind the trailer park dumpster",
		"with an ice cube",
		"at the Renaissance fair",
		"under the guise of night",
		"in a stranger's bed",
		"at the movie theater",
		"in a Turkish bath house",
		"while wearing a dog collar",
		"in a cage",
		"while pooping",
		"on all fours",
		"in the dressing room",
		"while sipping bourbon beside the roaring fire",
		"at Burning Man",
		"who are begging for it",
		"in exchange for diamonds",
		"on the metal table in the morgue",
		"and then summoning Lucifer",
		"on a hospital gurney",
		"while coated in aloe",
		"and stealing their fedoras",
		"on a swing",
		"in the back of a van",
		"but I haven't done that since the eighties",
		"tomorrow",
		"and never calling them for a second date",
		"while watching Twilight",
		"while talking like Shakespeare characters",
		"using a baby voice",
		"under water",
		"after a fight",
		"just like that one scene in Caligula",
		"and then we make a card game about it",
		"with foam everywhere",
		"who is pregnant",
		"in a high school planetarium",
		"after a storm",
		"while walking the dog",
		"while naked"
	};


}
